##----------------------------------------------------------------------------------------------------------------------------------#
# Script by : Brendon Reidy, 
# Special thanks. LLM AI for help writing the function for removing 0's and replacing them with NA's
# Project: 2024 Reu project/Living Collections Wood Archive 
# Purpose: To read raw data generated by manual measurments of tree ring width using the tellervo software.
# This scrip utilizes the dplR package (https://rdrr.io/cran/dplR/)to read files containing ringwidth measurments
# and their associated meta data house on the Forest Ecology Lab google drive. It then puts these data into 
# a form usable for analysis. 
# Inputs: Raw data from measurements collect via Forest Ecology Lab staff. These inputs include .CSV,
#.JSON, or .XML files in the Tridas format. This script utilizes .XML Files. Files are generated
# utlizing the software Tellervo (http://www.tellervo.org/) designed to collect and manage dendrochronological data and samples. 
# Outputs:comb1.rwl
# Notes: 
#---#At the time of writing, new collected data are not automated to upload onto on to the Forest Ecology Lab google drive.
#---#Data generated post the writing of this scipt will need to be uploaded on to the Forest Ecology Lab Drive
#---#This script presupposes a file path a file local to the user's googledrive where the Data input is housed

#---#Line 114 of this script removes a column due to user error in data entry, once this error is corrected that line
#must be removed.
######################################

library(dplR)

# Set working directory
# Until pathing errors are fixed on drive This will need to be the location of these data on the users local drive
setwd("~/Google Drive/My Drive/2024_REU_crossdate/Quercus RW Tridas")

# Function to process TRIDAS file
process.tridas.file <- function(file) {
  tridas.data <- read.tridas(file, ids.from.titles = TRUE, ids.from.identifiers = TRUE, 
                             combine.series = TRUE, trim.whitespace = TRUE, warn.units = TRUE)
  measurements <- tridas.data$measurements
  rwl.object <- as.rwl(measurements)
  return(rwl.object)
}

# There is an encoding error in several of the files, this 
# Funtion cleans non-UTF-8 characters from a files
clean.utf8 <- function(file) {
  raw.content <- readBin(file, "raw", file.info(file)$size)
  utf8.content <- iconv(rawToChar(raw.content), from = "latin1", to = "UTF-8", sub = "")
  temp.file <- tempfile(fileext = ".xml")
  writeLines(utf8.content, temp.file, useBytes = TRUE)
  return(temp.file)
}

#This section lists the XML files to check an ensure the data is consistent.
#It then cleans a process these files and stores them as .RWL objects
tridas.files <- list.files(pattern = ".xml$", full.names = TRUE)
print(tridas.files)  # Should list all XML files, expecting 112

# Create an empty list for storing RWL objects
rwl.objects <- list()

# Loop through each file, clean it, and process it
for (file in tridas.files) {
  cleaned.file <- clean.utf8(file)
 #cecking for errors with read in text visible in the console 
  tridas.data <- tryCatch({
    process.tridas.file(cleaned.file)
  }, error = function(e) {
    message("Error reading file:", file, "\n", conditionMessage(e))
    NULL
  })
  
  if (!is.null(tridas.data)) {
    rwl.objects[[file]] <- tridas.data
    cat("RWL object for", file, "created.\n")
  }
}
#####

#####
#This next section combines the individual RWL objest into a single data frame and aligns the 
#measurements by year
#####

# Print names in rwl.objects to check if there are 112
print(names(rwl.objects))

all.years <- unique(unlist(lapply(rwl.objects, rownames)))
all.years <- sort(as.numeric(all.years))

# Creates a data frame which will store the measurements
#From the rwl.objescts data frame around the "year" column as defined above.  
combined.rwl <- data.frame(year = all.years)

# Add measurements from each RWL object to the combined data frame
for (file in names(rwl.objects)) {
  measurements <- rwl.objects[[file]]
  file.name <- basename(file)
  
  # Create a data frame for the current file, Missing years will contain an NA
  df <- data.frame(year = as.numeric(rownames(measurements)), measurement = measurements[,1])
  
  # Merge with combined data frame by the "year" 
  combined.rwl <- merge(combined.rwl, df, by = "year", all.x = TRUE)
  
  # Rename the last column to the file name
  colnames(combined.rwl)[ncol(combined.rwl)] <- file.name
}

# Print combined RWL object names to check
print(colnames(combined.rwl))


# Set row names the the "year" and remove the year column
rownames(combined.rwl) <- combined.rwl$year
combined.rwl <- combined.rwl[, -1]
#check
print(colnames(combined.rwl))
#View(combined.rwl)
#############################################
# Remove column 73 due to data entry error
comb.rwl <- combined.rwl[, -73]
print(colnames(comb.rwl))
#############################################

# Find the first row to contain a value other than NA
dcomb.rwl <- which.max(apply(comb.rwl != "NA", 1, any))
#check to see the first rown in all columns to contain a non- NA value
head(comb.rwl[dcomb.rwl, ])

# Remove all rows previous to this
comb1.rwl <- comb.rwl[dcomb.rwl:nrow(comb.rwl), ]
#check to see if this matches the row in Head 
head(comb1.rwl)
#View(comb1.rwl)

#This next sextion will replace true "0" values with NA
#For some reason running this removes the years for my row names so preserving them first
rnames <- rownames(comb1.rwl)
for (i in 1:nrow(comb1.rwl)) {
  for (j in 1:ncol(comb1.rwl)) {
    if (!is.na(comb1.rwl[i, j]) && comb1.rwl[i, j] == "0") {
      comb1.rwl[i, j] <- NA
    }
  }
}
rownames(comb1.rwl) <- rnames
#check 
#View(comb1.rwl)

#checking the class of comb1.rwl to ensure it's a rwl file
class(comb1.rwl)
#assigning it the rwl classification as well
class(comb1.rwl) <- c("rwl", class(comb1.rwl))
#check
class(comb1.rwl)
coredat <- detrend(comb1.rwl, method = "Mean")  # Detrending
crs <- chron(coredat)  # Creating a chronology
# Print summary of the chronology
summary(crs)
# Plot the chronology
plot(crs, main = "Chronology")


